In [2]:
import numpy as np

In [4]:
a=np.array([1,2,3,])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
b=np.array(range(5))
print(b)
print(type(b))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [7]:
c=np.arange(3,18,3)
print(c)
print(type(c))
print(c.dtype)

[ 3  6  9 12 15]
<class 'numpy.ndarray'>
int32


In [8]:
d=np.arange(3,18,3,dtype=float)
print(d)
print(type(d))
print(d.dtype)

[ 3.  6.  9. 12. 15.]
<class 'numpy.ndarray'>
float64


In [11]:
e=d.astype("int32")
print(e)
print(type(e))
print(e.dtype)

[ 3  6  9 12 15]
<class 'numpy.ndarray'>
int32


In [20]:
import random
x=np.array([random.random() for i in range(5)])
print(x)
x=np.round(x,2)
print(x)

[0.31145458 0.51175965 0.27928466 0.76468556 0.47759405]
[0.31 0.51 0.28 0.76 0.48]


In [24]:
a=np.array([1,2,3])
print(a.shape)
b=np.array([[1,2,3],[4,5,6]])
print(b.shape)

(3,)
(2, 3)


In [33]:
print(b)
c=b.reshape(1,6)
print(c)
c=b.reshape(6,1)
print(c)
c=b.reshape((6,))
print(c)
c=b.flatten()
print(c)


[[1 2 3 4 5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [34]:
print(b)
c=b+2
print(c)
c=b*2
print(c)
c=b/2
print(c)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [35]:
c=np.arange(0,6).reshape(2,3)
print(b)
print(c)
d=b+c
print(d)


[[1 2 3]
 [4 5 6]]
[[0 1 2]
 [3 4 5]]
[[ 1  3  5]
 [ 7  9 11]]


In [36]:
c=np.arange(0,3)
print(b)
print(c)
d=b+c
print(d)

[[1 2 3]
 [4 5 6]]
[0 1 2]
[[1 3 5]
 [4 6 8]]


In [38]:
c=np.arange(0,2).reshape(2,1)
print(b)
print(c)
d=b+c
print(d)

[[1 2 3]
 [4 5 6]]
[[0]
 [1]]
[[1 2 3]
 [5 6 7]]


In [4]:
c=np.arange(0,6).reshape(2,3)
print(c)
d=c.transpose()
print(d)
d=c.T
print(d)
d=c.swapaxes(1,0)
print(d)


[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


In [12]:
c=np.arange(0,24).reshape(4,6)
print(c)
d=c[1]
print(d)
d=c[1:3]
print(d)
d=c[[1,3]]
print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 6  7  8  9 10 11]
[[ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[[ 6  7  8  9 10 11]
 [18 19 20 21 22 23]]


In [17]:
c=np.arange(0,24).reshape(4,6)
print(c)
d=c[1,:]
print(d)
d=c[2:,:]
print(d)
d=c[:,0]
print(d)
d=c[:,1:4]
print(d)
d=c[:,[1,3,4]]
print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 6  7  8  9 10 11]
[[12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[ 0  6 12 18]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]
[[ 1  3  4]
 [ 7  9 10]
 [13 15 16]
 [19 21 22]]


In [20]:
c=np.arange(0,24).reshape(4,6)
print(c)
d=c[3,4]
print(d)
d=c[1:3,2:5]
print(d)
d=c[[0,3,1],[1,2,5]]
print(d)
d=c[:,1:4]
print(d)
d=c[:,[1,3,4]]
print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
22
[[ 8  9 10]
 [14 15 16]]
[ 1 20 11]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]
[[ 1  3  4]
 [ 7  9 10]
 [13 15 16]
 [19 21 22]]


In [26]:
c=np.arange(0,24).reshape(4,6)
print(c)
c[c<10]=8
print(c)
c=np.arange(0,24).reshape(4,6)
print(c)
c=np.where(c<10,0,10)
print(c)
c=np.arange(0,24).reshape(4,6)
print(c)
c=c.clip(8,12)
print(c)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 8  8  8  8  8  8]
 [ 8  8  8  8 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  0  0  0  0  0]
 [ 0  0  0  0 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 8  8  8  8  8  8]
 [ 8  8  8  9 10 11]
 [12 12 12 12 12 12]
 [12 12 12 12 12 12]]


In [30]:
print(np.nan==np.nan)


False

In [39]:
c=np.arange(0,24).reshape(4,6).astype(float)
c[[0,3,1],[1,2,5]]=np.nan
print(c)
print(np.count_nonzero(c))
print(np.count_nonzero(c!=c))
print(np.count_nonzero(np.isnan(c)))
print(np.sum(c))
print(np.sum(c,axis=0))

[[ 0. nan  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. nan 21. 22. 23.]]
23
3
3
nan
[36. nan nan 48. 52. nan]


In [44]:
c=np.arange(0,24).reshape(4,6).astype(float)
c[[0,3,1],[1,2,5]]=np.nan
print(c)
for i in range(c.shape[1]):
    temp_col=c[:,i]
    num_nan=np.count_nonzero(temp_col!=temp_col)
    if num_nan!=0:
        not_nan=temp_col[temp_col==temp_col]
        temp_col[temp_col!=temp_col]=not_nan.mean()
print(c)
        

[[ 0. nan  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. nan 21. 22. 23.]]
[[ 0. 13.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19.  8. 21. 22. 23.]]


In [46]:
c=np.arange(0,24).reshape(4,6).astype(float)
d=np.arange(0,24).reshape(4,6).astype(float)
print(c)
print(d)
print(np.vstack((c,d)))
print(np.hstack((c,d)))

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.  0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.  6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17. 12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23. 18. 19. 20. 21. 22. 23.]]


In [49]:
c=np.arange(0,24).reshape(4,6).astype(float)
print(c)
c[[1,2],:]=c[[2,1],:]
print(c)
c[:,[2,4]]=c[:,[4,2]]
print(c)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [12. 13. 14. 15. 16. 17.]
 [ 6.  7.  8.  9. 10. 11.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  4.  3.  2.  5.]
 [12. 13. 16. 15. 14. 17.]
 [ 6.  7. 10.  9.  8. 11.]
 [18. 19. 22. 21. 20. 23.]]
